apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: k8s
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue:0.1tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 120
      previewReplicaCount: 1
